### ISSUE TITLE
Bump `flatstr`

### ISSUE THREAD

**Issue by chaffeqa** [mcollina/sonic-boom#26]
Ran into a bug in `flatstr` release `1.0.11`:

```SyntaxError: Unexpected token %
    at Pino.write (/node_modules/pino/lib/proto.js:137:21)
    at Pino.LOG [as error] (/node_modules/pino/lib/tools.js:34:21)
    at error (/src/server/services/primpy-feed.ts:120:14)
    at tryCatch (/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as throw] (/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _throw (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
^[[A^CSyntaxError: Unexpected token %
    at Pino.write (/node_modules/pino/lib/proto.js:137:21)
    at Pino.LOG [as info] (/node_modules/pino/lib/tools.js:35:26)
    at info (/src/server/logger.ts:83:14)
    at process.evtHandler (/src/server/logger.ts:107:30)
    at process.emit (events.js:200:13)
    at process.EventEmitter.emit (domain.js:471:20)
undefined:3
return typeof s === "string" ? %FlattenString(s) : s
                               ^

SyntaxError: Unexpected token %
    at Pino.write (/node_modules/pino/lib/proto.js:137:21)
    at Pino.LOG [as info] (/node_modules/pino/lib/tools.js:35:26)
    at info (/src/server/logger.ts:83:14)
    at process.evtHandler (/src/server/logger.ts:106:44)
    at process.emit (events.js:205:15)
    at process.EventEmitter.emit (domain.js:471:20)
    at process._fatalException (internal/process/execution.js:144:25)
```

Which you can trace back to the source added in that version of flatstr... anyways, it looks like `1.0.12` [fixes that](https://github.com/davidmarkclements/flatstr/commit/543c4513bbd490a9eb2b797419f1fd4240adb190#diff-168726dbe96b3ce427e7fedce31bb0bcL7).

Either way, pinning the version to the latest will prevent the bug i beleive

**Comment by mcollina** [comment]
We depend on the version range that include that fix. I don’t think any update is necessary here.
