### ISSUE TITLE
EAGAIN error thrown by SonicBoom.flushSync()

### ISSUE THREAD

**Issue by john-mills-nz** [mcollina/sonic-boom#51]
Hi

I'm using pino running inside an alpine docker container running on Windows and got the following error:

```
[2021-02-04 23:58:53.810 +0000] INFO     (shutDown/7 on 3f1660f33297): SIGINT signal received
[2021-02-04 23:58:53.812 +0000] ERROR    (errorLogging/7 on 3f1660f33297): uncaughtException occured
    error: {
      "type": "Error",
      "message": "EAGAIN: resource temporarily unavailable, write",
      "stack":
          Error: EAGAIN: resource temporarily unavailable, write
              at Object.writeSync (fs.js:711:3)
              at SonicBoom.flushSync (/app/node_modules/sonic-boom/index.js:285:8)
              at Proxy.<anonymous> (/app/node_modules/pino/lib/tools.js:375:18)
              at shutDown (/app/lib/shutDown.js:20:20)
              at process.<anonymous> (/app/lib/shutDown.js:31:42)
              at Object.onceWrapper (events.js:422:26)
              at process.emit (events.js:315:20)
              at process.wrappedEmit [as emit] (/app/node_modules/newrelic/lib/instrumentation/core/globals.js:56:23)
              at Signal.callbackTrampoline (internal/async_hooks.js:131:14)
      "errno": -11,
      "syscall": "write",
      "code": "EAGAIN"
    }
```
pino was configured with `pino(options, pino.destination({ sync: false }))` and a final logger was being used to log during app shutdown.

I think `flushSync()` needs EAGAIN retry logic similar to that of `release()`.

**Comment by mcollina** [comment]
Good spot, it does indeed!
